apiVersion: apps/v1
kind: Deployment
metadata:
  name: myaksapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myaksapp
  template:
    metadata:
      labels:
        app: myaksapp
    spec:
      containers:
      - name: myaksapp
        image: ${CONTAINER_REGISTRY}/myaksapp:${IMAGE_TAG}
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi